[package]
name = "fltk-builder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = "1"
lazy_static = "1"

[dev-dependencies]
fltk-anchor = "0.1"
fltk-theme = "0.4"