name: Pullrequest-Workflow

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-pullrequest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-10.15, ubuntu-18.04, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Build release
      run: cargo build --verbose --release
    - name: Build docs
      run: cargo doc --verbose
    - name: Build docs release
      run: cargo doc --verbose --release
    - name: Run tests
      run: cargo test --verbose
