name: Rust

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
